[package]
name = "phrasic"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "phrasic"
path = "src/main.rs"

[dependencies]
phrasic-core = { path = "../phrasic-core" }
phrasic-rpc = { path = "../phrasic-rpc" }
tokio = { version = "=1.53.0", features = ["io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "=0.1.18", features = ["net"] }
tokio-util = { version = "=0.7.18", features = ["rt"] }
toml = "=0.8.23"
tonic = { version = "=0.14.6", features = ["transport"] }
fs2 = "=0.4.3"
hyper-util = { version = "=0.1.20", features = ["tokio"] }
tower = "=0.5.3"
url = "=2.5.7"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "=0.30.1", features = ["user"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "=0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_System_Threading"] }

[dev-dependencies]
tempfile = "=3.27.0"

[lints]
workspace = true
